seed: 42
experiment_name: "cc3m_llava"

data:
  caption_files: ["captions.json"]
  num_workers: 16
  val_split_num: 50000
  precomputed_features_dir: "precomputed_features"
  dataset_dir: "datasets"

model:
  embedding_space_dim: 768
  vision_encoder: "dinov2_vitl14"  
  vision_projector:
    hidden_size: 4096
    num_layers: 0
    normalize: True
  language_encoder: "openai/clip-vit-large-patch14"
  language_projector:
    hidden_size: 4096
    num_layers: 4
    normalize: True
    dropout: 0.1

training:
  max_steps: 5000
  lr_warmup_steps: 150
  learning_rate: 0.001
  lr_schedule: "cosine"
  batch_size: 1024
  accumulate_grad_batches: 1
  max_grad_norm: 1
  weight_decay: 0.0001
  early_stopping: True
  early_stopping_patience: 50
  early_stopping_min_delta: 0.001
  num_gpus: 1

skip_test: true

logging:
  save_dir: "logs/"
  save_checkpoint: True
  log_every_n_steps: 10
  val_check_interval: 500
